### ISSUE TITLE
Can't install plugin on Apple Silicon (ARM)

### ISSUE THREAD

**Issue by sammcj** [rewanth1997/kubectl-fields#2]
I'm trying to use this on my M1 Macbook Pro, Apple is in the process of moving from Intel to ARM and thus software needs to be built with both targets.

Is it possible for you to add an Apple Silicon / ARM build for this?

```
 ~ kubectl krew install fields
Updated the local copy of plugin index.
Installing plugin: fields
W0829 13:30:35.534705    9440 install.go:164] failed to install plugin "fields": plugin "fields" does not offer installation for this platform
F0829 13:30:35.534761    9440 root.go:79] failed to install some plugins: [fields]: plugin "fields" does not offer installation for this platform
```

**Comment by rewanthtammana** [comment]
Apologies for being late here. I will release this asap. @sammcj @toast-gear @brantb

**Comment by rewanthtammana** [comment]
@sammcj @toast-gear @brantb ARM support is available now!

**Comment by sammcj** [comment]
Woop woop! Nice work - thanks :D
