### ISSUE TITLE
No longer diplays full hierarchy

### ISSUE THREAD

**Issue by diepfote** [rewanth1997/kubectl-fields#3]
Works against a server version 1.11.0.  
Does not work against 1.24.10. (used the same kubectl version against both)

```
$ k fields pod readiness
readinessProbe
readinessProbe
readinessProbe
-required-.readinessGates
```

kubectl version 1.27.1
server version 1.24.10-eks

---

have you seen this before?

would be great to get some feedback :)

**Comment by rewanthtammana** [comment]
@diepfote I just tested it against 1.26.0. Just to be sure, I cloned the repo & built it again. It seems to be working fine.

![image](https://github.com/rewanthtammana/kubectl-fields/assets/22347290/56fbb6e8-deb5-428b-a98d-58201ba72526)

Alternatively, just for testing, you can build the code from source, move the binary to /usr/local/bin & see if its working or not.

```bash
go build -o kubectl-fields main.go
sudo mv kubectl-fields /usr/local/bin
k fields pod readiness
```

<img width="1280" alt="image" src="https://github.com/rewanthtammana/kubectl-fields/assets/22347290/bcb72a7e-4083-4e3f-8c5f-5c63f8b58e92">

**Comment by diepfote** [comment]
Tested it again, same issue. Maybe it is because it's an EKS kubernetes distribution.

Thanks for checking though
